site_name: OpenIPC
site_url: https://openipc.github.io/
repo_url: https://github.com/OpenIPC/openipc.github.io
repo_name: openipc.github.io/docs
edit_uri: blob/main/docs
copyright: Copyright &copy; <a href="https://openipc.org"  target="_blank" rel="noopener">OpenIPC team</a>, 2021


theme:
  name: material
  language: en
  favicon: images/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        primary: teal
        accent: red
  features:
    - navigation.instant
    - toc.integrate
#    - navigation.expand


plugins:
  - search:
      lang:
        - en
        - ru


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.betterem
  - toc:
      permalink: true


extra:
  social:
    - icon: fontawesome/solid/mail-bulk
      link: mailto:dev@openipc.org
    - icon: fontawesome/brands/telegram
      link: https://t.me/openipc
    - icon: fontawesome/brands/github
      link: https://github.com/openipc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openipc
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCaXlbR2uGTRFh8jQ2lCFd2g


extra_css:
  - stylesheets/extra.css
  - 'assets/css/zftlab.css'


extra_javascript:
  - 'assets/js/yandex.js'


nav:
  - "Introduction": index.md
  - "Wiki for new OpenIPC 2.1 (BR)": https://github.com/OpenIPC/firmware/wiki
  - "Notes for old OpenIPC 1.0 (Wrt)": manual.md
  - "Support OpenSource": sponsor.md
#  - Language support:
#    - "English": /
#    - "Русский": /
